version: "3"
services:
    app:
       build:
           context: .
       ports:
           -  "9095"
    nginx:
        image: nginx:latest
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - single-webpage-app
        ports:
        - "8585:80"