version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          command: |
            aws cloudformation deploy \
            --template infra/ecs/resources.yaml \
            --stack << parameters.stack-name >> \
            --parameter-overrides ImageTag=${CIRCLE_SHA1} \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset        

## Commit to a branch
commit: &only_commit
  filters:
    branches:
        only:
            - /feat.*/
            - /fix.*/


workflows:
  version: 2

#Dev deployment
  deploy-dev:
    jobs:
      - deploy-cfn:
          context: devops-playground-context
          <<: *only_commit
          stack-name: My-Web-Application