version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          command: |
            aws cloudformation deploy \
            --template infra/ecs/resources.yaml \
            --stack << parameters.stack-name >> \
            --parameter-overrides ImageTag=${CIRCLE_SHA1}            

workflows:
  deploy:
    - … # build image and push to ECR with ${CIRCLE_SHA1} tag
    - deploy-cfn:
      context:
        - aws-12345-us-east-2
      stack-name: My-Application