version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          command: |
            aws cloudformation deploy \
            --template infra/ec2/resources.yaml \
            --stack << parameters.stack-name >> \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset   
            
  deploy-app:
    # parameters:
    #   stack-name:
    #     description: Name of the CloudFormation stack
    #     type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - add_ssh_keys:
          fingerprints:
            - "SHA256:O69Gv5ckRihn9ejbRXyb8I1vg517YgoKuM6BpsGaz1g"
      - run:
          name: Deploy application
          command: |
            PUBLIC_IP=$(curl ipinfo.io/ip)
            AWS_REGION=$AWS_REGION
            EC2_USERNAME=ec2_user
            EC2_PUBLIC_DNS=$EC2_PUBLIC_DNS
            ssh -oStrictHostKeyChecking=no -v $EC2_USERNAME@$EC2_PUBLIC_DNS "./deploy.sh"

## Commit to a branch
commit: &only_commit
  filters:
    branches:
        only:
            - /feat.*/
            - /fix.*/

## Commit to a branch
only_on_infra_branch: &only_infra_commit
  filters:
    branches:
        only:
            - infra

workflows:
  version: 2

#Dev infra
  deploy-infra:
    jobs:
      - deploy-cfn:
          context: devops-playground-context
          <<: *only_commit
          stack-name: ec2-infra-stack

#Dev app
  deploy-application:
    jobs:
      - deploy-app:
          context: devops-playground-context
          <<: *only_commit
          