version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "9095"
  nginx:
    image: nginx:1.25.4-alpine-perl
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8990:80"
